name: Documentation typesetting

# Currently we run in two situations:
on:
  # Whenever someone pushes to a branch in our repo
  push:
    branches:
      - "*"
  # Whenever a pull request is opened, reopened or gets new commits.
  pull_request:
# This implies that for every push to a local branch in our repo for which a
# pull request is open this runs twice. But it's important to ensure that pull
# requests get tested even if their branch comes from a fork.
# Also the PR check runs on the merged commit, not on the unmerged branch.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: .github/tl_packages
          cache_version: 2
      - name: Checkout fonts for testing
        uses: actions/checkout@v4
        with:
          repository: wspr/fontspec-test-fonts
          path: fontspec-test-fonts
      - name: Install fonts for testing
        run: ./fontspec-test-fonts/install.sh
      - name: Documentation
        run: l3build doc -q -H --show-log-on-error
        artifact_name: Documentation
      # Now we create the artifacts: There are two cases where this happens.
      # 1. If we failed running tests
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: Documentation
          retention-days: 3
      # 2. If we succeed building documentation
      - name: Archive documentation
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "**/*.pdf"
          retention-days: 21
